import Head from "next/head"
import Layout from "@/components/Layout"

export default function About() {
  return (
    <div>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <h2>Sobre</h2>
        </main>
      </Layout>
    </div>
  )
}
