import Head from "next/head"
import Layout from "@/components/Layout"

export default function Dashboard() {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Layout>
        <main>
          <h2>Dashboard</h2>
        </main>
      </Layout>
    </div>
  )
}
