import Head from "next/head"
import Layout from "@/components/Layout"
import {getCookie} from "cookies-next"
import {useRouter} from "next/router"
import {useEffect} from "react"
import {verifyToken} from "@/services/users"

export default function Dashboard() {
  const router = useRouter()
  const token = getCookie("jwt_authorization")

  useEffect(() => {
    if (!token) {
      router.push("/signin")
    }
  }, [])

  //TODO: verificar token

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Layout>
        <main>
          <h2>Dashboard</h2>
        </main>
      </Layout>
    </div>
  )
}
