import {useState} from "react"
import axios from "axios"
import Head from "next/head"
import styles from "@/styles/Home.module.css"
import Layout from "@/components/LayoutCardSignIn"
import Input from "@/components/input/input"
import Button from "@/components/button/button"
import Link from "next/link"
import Select from "@/components/select/select"

export default function signUp() {
  const [form, setForm] = useState("")
  const [message, setMessage] = useState("")
  const [type, setType] = useState("")

  const handleSubmit = async (e) => {
    try {
      e.preventDefault()
      const resp = await axios.post("/api/users/cadastro", form)
      const json = await resp.data

      if (resp.status !== 201) throw new Error(json)

      setMessage("Usuário cadastrado com sucesso")
      setType("success")
    } catch (error) {
      setMessage(error.response.data)
      setType("error")
    }
  }

  const handleChange = (e) => {
    setForm({...form, [e.target.name]: e.target.value})
  }

  const handleMessageClick = () => {
    setMessage("")
  }

  return (
    <>
      <Head>
        <title>App test | Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Layout>
        <div className={styles.title}>
          <h2>Cadastro de usuário!</h2>
        </div>
        <form onSubmit={handleSubmit}>
          <div>
            <Input
              text="Nome"
              type="text"
              name="name"
              id="text"
              value={form.name ? form.name : ""}
              placeholder="Informe seu nome"
              onChange={handleChange}
              required
            />
            <Input
              text="Email"
              type="email"
              name="email"
              id="email"
              value={form.email ? form.email : ""}
              placeholder="Informe seu email"
              onChange={handleChange}
              required
            />
            <Input
              text="Senha"
              type="password"
              name="password"
              id="password"
              value={form.password ? form.password : ""}
              placeholder="Informe sua senha"
              onChange={handleChange}
              required
            />
            <Select name="level" text="Nível" />
          </div>
          {message && (
            <div onClick={handleMessageClick} className={`${styles.message} ${styles[type]}`}>
              {message}
            </div>
          )}
          <div className={styles.footer}>
            <Link className={styles.link} href="/signin">
              Já tenho conta.
            </Link>
          </div>
          <Button text="Cadastrar" type="submit" />
        </form>
      </Layout>
    </>
  )
}
