import styles from "@/styles/Home.module.css"
import Layout from "@/components/LayoutCardSignIn"
import Input from "@/components/input/input"
import Button from "@/components/button/button"
import Link from "next/link"
import Head from "next/head"
import {useState} from "react"
import {getUser} from "./api/users"
import { useRouter } from "next/router"

export default function signIn() {
  const router = useRouter()
  const [form, setForm] = useState("")

  const handleSubmit = async (e) => {
    e.preventDefault()
    const res = await getUser(form)
    if(res){
      console.log('Usuário autenticado!')
      router.push('/')
    }
  }

  const handleChange = (e) => {
    setForm({...form, [e.target.name]: e.target.value})
  }

  const handleCheckboxChange = (e) => {
    setForm({...form, [e.target.name]: e.target.checked})
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.title}>
          <h2>Bem-vindo(a) de volta!</h2>
        </div>
        <form onSubmit={handleSubmit}>
          <div>
            <Input text="Email" name="email" type="email" placeholder="Informe seu email" onChange={handleChange} />
            <Input
              text="Senha"
              name="password"
              type="password"
              placeholder="Informe sua senha"
              onChange={handleChange}
            />
          </div>
          <div className={styles.footer}>
            <div className={styles.remember}>
              <input type="checkbox" name="remember" id="remember" onChange={handleCheckboxChange} />
              <span>Lembrar-me</span>
            </div>
            <div>
              <Link className={styles.link} href="/signup">
                Não tem conta? Cadastrar!
              </Link>
            </div>
          </div>
          <Button text="Entrar" type="submit" />
        </form>
      </Layout>
    </>
  )
}
