import Head from "next/head"
import Image from "next/image"
import styles from "@/styles/Home.module.css"
import Layout from "@/components/layout"
import Input from "@/components/input/input"
import Button from "@/components/button/button"
import Link from "next/link"

export default function signUp() {
  return (
    <>
      <Head>
        <title>App test | Registrar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.title}>
          <h2>Faça seu cadastro!</h2>
        </div>
        <form action="">
          <div>
            <Input text="Nome" type="text" value="" placeholder="Informe seu nome" />
            <Input text="Email" type="email" value="" placeholder="Informe seu email" />
            <Input text="Senha" type="password" value="" placeholder="Informe sua senha" />
          </div>
          <Button text="Registrar" type='submit'/>
        </form>
      </Layout>
    </>
  )
}
