import {useState} from "react"
import Head from "next/head"
import styles from "@/styles/Home.module.css"
import Layout from "@/components/LayoutCardSignIn"
import Input from "@/components/input/input"
import Button from "@/components/button/button"
import Link from "next/link"
import {createUser} from "./api/users"

export default function signUp() {
  const [form, setForm] = useState("")
  const [message, setMessage] = useState("")

  const handleSubmit = async (e) => {
    e.preventDefault()
    try {
      const user = await createUser(form)
      //TODO: PEGAR RETORNO USUÁRIO DA API

      setForm("")
      setMessage(`Usuário cadastrado!`)
    } catch (error) {
      console.error(error)
    }
  }

  const handleChange = (e) => {
    setForm({...form, [e.target.name]: e.target.value})
  }

  const handleMessageClick = () => {
    setMessage("")
  }

  return (
    <>
      <Head>
        <title>App test | Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.title}>
          <h2>Faça seu cadastro!</h2>
        </div>
        <form onSubmit={handleSubmit}>
          <div>
            <Input
              text="Nome"
              type="text"
              name="name"
              id="text"
              value={form.name ? form.name : ""}
              placeholder="Informe seu nome"
              onChange={handleChange}
            />
            <Input
              text="Email"
              type="email"
              name="email"
              id="email"
              value={form.email ? form.email : ""}
              placeholder="Informe seu email"
              onChange={handleChange}
            />
            <Input
              text="Senha"
              type="password"
              name="password"
              id="password"
              value={form.password ? form.password : ""}
              placeholder="Informe sua senha"
              onChange={handleChange}
            />
          </div>
          {message ? (
            <div onClick={handleMessageClick} className={styles.success}>
              {message}
            </div>
          ) : (
            ""
          )}
          <div className={styles.footer}>
            <Link className={styles.link} href="/signin">
              Já tenho conta.
            </Link>
          </div>
          <Button text="Cadastrar" type="submit" />
        </form>
      </Layout>
    </>
  )
}
